# Generated by Django 4.2.6 on 2023-10-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y', verbose_name='Изображение'),
        ),
    ]
